//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radiologija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database : DbContext
    {
        public Database()
            : base("name=Database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hospital> hospital { get; set; }
        public virtual DbSet<maska> maska { get; set; }
        public virtual DbSet<modalitet> modalitet { get; set; }
        public virtual DbSet<nalazDefault> nalazDefault { get; set; }
        public virtual DbSet<doktor> doktor { get; set; }
        public virtual DbSet<nalaz> nalaz { get; set; }
        public virtual DbSet<operater> operater { get; set; }
    }
}
