//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radiologija
{
    using System;
    using System.Collections.Generic;
    
    public partial class nalazDefault
    {
        public int id_nalazDefault { get; set; }
        public int id_modalitet { get; set; }
        public int id_maska { get; set; }
        public string naziv { get; set; }
        public string tekst { get; set; }
    
        public virtual maska maska { get; set; }
        public virtual modalitet modalitet { get; set; }
    }
}
