//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radiologija
{
    using System;
    using System.Collections.Generic;
    
    public partial class nalaz
    {
        public int id_nalaz { get; set; }
        public int id_modalitet { get; set; }
        public int id_hospital { get; set; }
        public int id_maska { get; set; }
        public Nullable<int> id_doktor { get; set; }
        public Nullable<int> id_operater { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public Nullable<System.DateTime> datum_rodj { get; set; }
        public System.DateTime datum_pregleda { get; set; }
        public string napomena { get; set; }
        public string nalaz_tekst { get; set; }
    
        public virtual doktor doktor { get; set; }
        public virtual hospital hospital { get; set; }
        public virtual maska maska { get; set; }
        public virtual modalitet modalitet { get; set; }
        public virtual operater operater { get; set; }
    }
}
